name: Deploy to railway DEV Environtment

on: 
  push:
    branches:
      - "develop"

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: action/checkout@v2

      - name: Install NodeJS 20.x
        uses: action/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Package
        run: npm install

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}

      
